=== lukaszgaza/winhacplusplus/farm/jobs/4/input/InputData.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Sat Feb 21 14:58:11 CET 2009 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Created with EditiX (http://www.editix.com) at Thu Feb 12 17:05:12 CET 2009</xs:documentation>
	</xs:annotation>
	<xs:element name="inputData">
		<xs:annotation>
			<xs:documentation>This is a *INHAC input data XML scheme.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element ref="constants"/>
				<xs:element ref="generatorSettings"/>
				<xs:element ref="eventSettings"/>
				<xs:element ref="persistency"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="constants">
		<xs:annotation>
			<xs:documentation>Collection of physics and mathematics constants.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="constMath"/>
				<xs:element ref="constPhys"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="constMath">
		<xs:complexType>
			<xs:all>
				<xs:element default="3.14159265" name="pi" type="xs:double"/>
				<xs:element name="invGeV2toNb"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="constPhys">
		<xs:complexType>
			<xs:all>
				<xs:element name="sinThetaW2" type="xs:double"/>
				<xs:element default="137.035999679" name="invAlphaQED" type="xs:double">
					<xs:annotation>
						<xs:documentation>1/alpha_QED</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="FermiConst">
					<xs:annotation>
						<xs:documentation>Fermi Constant [GeV^{-2}]</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.1176" name="alphaQCD" type="xs:double">
					<xs:annotation>
						<xs:documentation>QCD coupling constant at M_Z</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="matrixCMK"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="matrixCMK">
		<xs:annotation>
			<xs:documentation> Values of the CKM matrix elements from 2008 PDG Review: Eq. (11.27) for central values of the parameters  (only real parts of the matrix elements are taken)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element default="0.97419" name="VCKM_11" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_ud  real par</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.22570" name="VCKM_12" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_us  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.00359" name="VCKM_13" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_ub  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="-0.22560" name="VCKM_21" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_cd  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.97334" name="VCKM_22" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_cs  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.04150" name="VCKM_23" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_cb  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.00874" name="VCKM_31" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_td  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="-0.04070" name="VCKM_32" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_ts  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element default="0.999133" name="VCKM_33" type="xs:double">
					<xs:annotation>
						<xs:documentation>V_tb  real part</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="generatorSettings">
		<xs:annotation>
			<xs:documentation>Monte Carlo generator settings (Random number generator settings, printouts)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="randomGenrator"/>
				<xs:element ref="printOut"/>
				<xs:element name="maxWeightRej">
					<xs:annotation>
						<xs:documentation>maximum weight for rejection</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:all>
			<xs:attribute default="10000" name="nbEvents" type="xs:long"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="randomGenrator">
		<xs:annotation>
			<xs:documentation>Random generator settings (name, seed).</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="seed"/>
			</xs:all>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="printOut">
		<xs:annotation>
			<xs:documentation>Type of a printout.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="prinOutType" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="eventSettings">
		<xs:complexType>
			<xs:all>
				<xs:element ref="beamStettings"/>
				<xs:element ref="hardProcess"/>
				<xs:element ref="radiativeCorrections"/>
				<xs:element ref="externalPackages"/>
			</xs:all>
			<xs:attribute name="eventType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="weighted"/>
						<xs:enumeration value="unweighted"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="beamStettings">
		<xs:complexType>
			<xs:all>
				<xs:element ref="beamA"/>
				<xs:element ref="beamB"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="beamA">
		<xs:complexType>
			<xs:all>
				<xs:element ref="beamParticle"/>
			</xs:all>
			<xs:attribute default="7000" name="energy">
<!--
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minInclusive value="0."/>
					</xs:restriction>
				</xs:simpleType>
				-->
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="beamB">
		<xs:complexType>
			<xs:all>
				<xs:element ref="beamParticle"/>
			</xs:all>
			<xs:attribute name="energy"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="beamParticle">
		<xs:complexType>
			<xs:all>
				<xs:element ref="idPDG" />
				<xs:element minOccurs="0" ref="particleName" />
				<xs:element ref="PDF" />
				<xs:element ref="heavyIon" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="idPDG" type="xs:integer"/>
	<xs:element name="particleName" type="xs:string"/>
	<xs:element name="PDF">
		<xs:complexType>
			<xs:all>
				<xs:element name="xMin">
					<xs:annotation>
						<xs:documentation>
							minimum of quarks x&apos;s
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="xMax">
					<xs:annotation>
						<xs:documentation>
							maximum of quarks x&apos;s
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Q2min">
					<xs:annotation>
						<xs:documentation>
							minimum of quarks Q^2 [GeV^2]
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PDFsubset" type="xs:int"></xs:element>
			</xs:all>
			<xs:attribute name="name" type="xs:string"></xs:attribute>
			<xs:attribute name="PDFinterface" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="heavyIon">
		<xs:complexType>
			<xs:all>
				<xs:element name="chargeNb">
					<xs:annotation>
						<xs:documentation>Charge number of ion beam</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="atomicNb">
					<xs:annotation>
						<xs:documentation>Atomic number of ion beam</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="energy">
					<xs:annotation>
						<xs:documentation>Energy/nucleon for ion beam in GeV</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nuclearCorre" type="xs:int">
					<xs:annotation>
						<xs:documentation>choice of nuclear corrections
0: No nuclear shadowing effects
1: EKS98 nuclear shadowing effects</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:all>
			<xs:attribute ref="switchOn"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hardProcess">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="bosons">
					<xs:annotation>
						<xs:documentation>The intermediate bosons in the Drell-Yan like process choice</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="intermidiateBosons">
								<xs:annotation>
									<xs:documentation>List of PDG ids of the intermediate bosons in the Drell-Yan like process</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:choice>
										<xs:element maxOccurs="unbounded" ref="particleName"/>
										<xs:element maxOccurs="unbounded" ref="idPDG"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element default="Unpolarized" name="polarization">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Longitudinally"/>
										<xs:enumeration value="Transversely"/>
										<xs:enumeration value="Unpolarized"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="initialParticles">
					<xs:annotation>
						<xs:documentation>choice of initial particles</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice>
							<xs:element maxOccurs="unbounded" ref="particleName"/>
							<xs:element maxOccurs="unbounded" ref="idPDG"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="finialParticles">
					<xs:complexType>
						<xs:choice>
							<xs:element maxOccurs="unbounded" ref="particleName"/>
							<xs:element maxOccurs="unbounded" ref="idPDG"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="widthSchem">
					<xs:annotation>
						<xs:documentation>boson width scheme (fixed or running)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="witdthType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="fix"/>
									<xs:enumeration value="running"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="ips">
					<xs:annotation>
						<xs:documentation> input-parameter scheme (alpha-scheme or G_mu-scheme)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="ipsScheme" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="alpha"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="factorizationScale">
					<xs:annotation>
						<xs:documentation> Factorization scale choice muF**2 = Q**2 = s&apos; or muF**2 = Mboson**2</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="scaleType" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="muF^2=Q^2"/>
									<xs:enumeration value="muF^2=Mw^2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="radiativeCorrections">
		<xs:annotation>
			<xs:documentation>Radiative corrections switches</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="ewCorrections">
					<xs:complexType>
						<xs:all>
							<xs:element name="correctionType">
								<xs:annotation>
									<xs:documentation>Radiative correction switch:
1: Above + QED radiative correction in W-decay    
2: Above + O(alpha) electroweak (EW) corrections 
3: QED correction for q + q~ -&gt; Boson -&gt; l + v 
4: QED+EW correction for q + q~ -&gt; Boson -&gt; l + v</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:all>
						<xs:attribute ref="switchOn"/>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="externalPackages">
		<xs:annotation>
			<xs:documentation>Settings for an external packages.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="partonShower"/>
				<xs:element ref="hadronization"/>
				<xs:element ref="rootAnalysisTool"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="partonShower">
		<xs:complexType>
			<xs:attribute ref="switchOn"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="hadronization">
		<xs:complexType>
			<xs:attribute ref="switchOn"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="rootAnalysisTool">
		<xs:complexType>
			<xs:attribute ref="switchOn"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="persistency">
		<xs:complexType>
			<xs:attribute ref="switchOn"/>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="switchOn">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="on"/>
				<xs:enumeration value="off"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
</xs:schema>

=== lukaszgaza/winhacplusplus/input.backup/UserFile.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Sat Feb 21 14:58:11 CET 2009 -->

<inputData
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="InputData.xsd">
<!-- ================== Constans =================-->	 
		<constants>
		<constMath>
			<pi>3.1415926535897932</pi>
			<invGeV2toNb>389379.304 </invGeV2toNb>
		</constMath>
		<constPhys> 
			<sinThetaW2>-0.2222</sinThetaW2> 
			<invAlphaQED>137.03599968</invAlphaQED>
			<FermiConst>1.16637e-5</FermiConst>
			<alphaQCD>0.1176</alphaQCD>
			<matrixCMK>
				<VCKM_11>0.97419 </VCKM_11>
				<VCKM_12>0.22570 </VCKM_12>
				<VCKM_13>0.00359 </VCKM_13>
				<VCKM_21>-0.22560 </VCKM_21>
				<VCKM_22>0.97334 </VCKM_22>
				<VCKM_23>0.04150 </VCKM_23>
				<VCKM_31>0.00874 </VCKM_31>
				<VCKM_32>-0.04070</VCKM_32>
				<VCKM_33>0.999133</VCKM_33>
			</matrixCMK>
		</constPhys>
	</constants>
<!-- =============== Generator Settings===============-->
	<generatorSettings nbEvents="10000">
	
		<randomGenrator name="ranlux"/>
		<printOut prinOutType="1"></printOut>
		<maxWeightRej>2.0</maxWeightRej>
	</generatorSettings>	
<!-- ================= Event Settings================-->	
	<eventSettings>
<!-- ================= Beam Settings================-->		
		<beamStettings>
			<Q2minCut>1.69</Q2minCut>
			<beamA energy="7000"> 
				<beamParticle>
					<idPDG>2212</idPDG>
					<PDF name="cteq61" PDFinterface="LHAPDF">
						<PDFsubset>0</PDFsubset>		
						<xMin>1e-6</xMin> 
						<xMax>1.0</xMax>
					</PDF>
					<heavyIon switchOn="off">
						<atomicNb></atomicNb>
		 				<chargeNb></chargeNb>
		 				<energy></energy>
		 				<nuclearCorre>0</nuclearCorre>
					</heavyIon>
				</beamParticle>
			</beamA>
			<beamB energy="7000">
				<beamParticle>
					<idPDG>2212</idPDG>
					<PDF PDFinterface="LHAPDF" name="cteq61">
						<PDFsubset>0</PDFsubset>		
						<xMin>1e-6</xMin> 
						<xMax>1.0</xMax>
					</PDF>
					<heavyIon switchOn="off">
						<atomicNb></atomicNb>
		 				<chargeNb></chargeNb>
		 				<energy></energy>
		 				<nuclearCorre>0</nuclearCorre>
		 			</heavyIon>
				</beamParticle>
			</beamB>
		</beamStettings>
<!-- ================ Hard Process=================-->
		<hardProcess>
			<bosons>
				<intermidiateBosons>
					<particleName>W-</particleName>
					<particleName>W+</particleName>
				</intermidiateBosons>
				<polarization>Unpolarized</polarization>
			</bosons>
			<initialParticles>
				<particleName>u</particleName>
				<particleName>ubar</particleName>
				<particleName>d</particleName>
				<particleName>dbar</particleName>
				<particleName>c</particleName>
				<particleName>cbar</particleName>
				<particleName>s</particleName>
				<particleName>sbar</particleName>
				<particleName>b</particleName>
				<particleName>bbar</particleName>
				<particleName>t</particleName>
				<particleName>tbar</particleName>			
			</initialParticles>
			<finialParticles>
				<particleName>e</particleName>
				<particleName>mu</particleName>
			</finialParticles>
			<widthSchem  witdthType="fix"></widthSchem>
			<ips ipsScheme="alpha">1</ips>
			<factorizationScale scaleType="muF^2=Q^2">0</factorizationScale>
		</hardProcess>
		<radiativeCorrections>
			<ewCorrections switchOn="off">
				<correctionType>2</correctionType>
			</ewCorrections>
		</radiativeCorrections>
	</eventSettings>
</inputData>
